language: php

php:
  - 5.6
  - 7.2

install:
  - composer install
script:
  - vendor/bin/phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master