language: php

php:
  - 5.6
  - 7.2
  - 7.4

install:
  - composer install
script:
  - vendor/bin/phpunit

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master